CREATE TABLE REDCAP_ANSWER_MAPPING (
	PROJECT_ID NUMBER,
	FIELD_NAME VARCHAR2(100),
	FORM_NAME VARCHAR2(100),
	ANSWER_TEXT VARCHAR2(2000),
	CONCEPT_CD VARCHAR2(50),
	PRO_ITEM_LOINC VARCHAR2(50),
	PRO_MEASURE_LOINC VARCHAR2(50),
	IS_DATE_FIELD NUMBER(1)
);
